### ISSUE TITLE
Unintended Ejection

### ISSUE THREAD

**Issue by Thann** [David20321/7DFPS#1]
On the Glock and 1911, If you clear the gun, lock the slide back, insert a loaded mag, then press R to rack/release the slide, sometimes the top round will be ejected. This only happens sometimes, and I'm not sure why.

**Comment by Kroporo** [comment]
Was fixed in 496bdb03303884fff19d105124ec9bfec25698cc.
Issue can be closed.

**Comment by Thann** [comment]
7 day FPS, and a 7 year bugfix ^>^
