### ISSUE TITLE
Rebinding keys do not change instructions in-game

### ISSUE THREAD

**Issue by alexschrod** [David20321/7DFPS#10]
As I don't have an American keyboard, most of the non-alphanumeric keys you've chosen for certain things (like ? and ~) are either Shift+<key> or even a [dead key](https://en.wikipedia.org/wiki/Dead_key), and so I had to rebind them. Thanks for providing that feature in your launcher, a lot of games just assume everyone's an American.

However, in the game, it still says to press the original keys, not my rebound keys. I bound holster to comma(,) help to dash(-) and reset game to period(.), but in the game, it still tells me to press ? for help, and to press ~ for holster and to hold l for reset.

It's a bit confusing, to say the least. Shouldn't you update your in-game instructions when the bindings are changed?

**Comment by autious** [comment]
This can hopefully be fixed with the next major version of Unity.

**Comment by Kroporo** [comment]
This has been resolved in #144
Issue can be closed @autious
