### ISSUE TITLE
Floating Bullet Bug

### ISSUE THREAD

**Issue by mossarelli** [David20321/7DFPS#5]
I think this has been mentioned on the forum but there was no issue about it here.

If David or whoever is working on this game decides to fix it, you can just tick this issue fixed.

Describe the problem:
Pulling the slide back with "R" and then inserting a magazine with bullets and then taking out the magazine will result in the bullet from the magazine to be floating near the feeding ramp.

Letting the slide forward by releasing "R" will then have successfully loaded the gun.

The same bug can be created while having the slide locked with the slide catch, inserting a loaded magazine and then taking it out again. However, most people won't notice this bug while dry reloading because the chamber cannot be visually seen after a dry reload.

Gunsmith's rant:
A bullet never leaves the magazine until the slide pushes it forward from the magazine into the feeding ramp and into the chamber.

Exceptions for this rule are:
Chamber loaded pistols and shotguns.
Revolver guns with cylinder.
Pump & Semi-Auto Shotguns with tube.
Machineguns with linked bullet casings.
Harpoon rifles.

Suggestion:
It would create some more bugs but would make gameplay realistic:
Create a 0 to 100% distance the bullet must travel from the magazine to the chamber. If you release the slide and then quickly pull it back again, a bullet may be stuck at 40% and in order to fix it, the player must remove the magazine, holster the pistol, press z to push it back in again or make a new key to remove the bullet.

If the slide is released to the point where the bullet is no longer under the magazine's spring tension and then quickly pulled back again, the next bullet in the magazine will be at the top position in the magazine. Releasing the slide at this point will create a double feed which will jam the gun. If there's a bullet in the chamber at this point, the slide will have to be moved forward with the magazine taken out, to catch the bullet sitting in with the extractor and then pulled back to successfully remove it.

Thanks for the awesome game.

**Comment by Kroporo** [comment]
Was fixed in 496bdb03303884fff19d105124ec9bfec25698cc.
Issue can be closed.
