### ISSUE TITLE
Broken controls on linux

### ISSUE THREAD

**Issue by MariR** [David20321/7DFPS#9]
When used the help-control ("?") on Linux the player/character jumps and shoots:
http://www.youtube.com/watch?feature=player_embedded&v=60f_djFlyKw (this video is not made by me). I'm using a German Keyboard/Keyboard-layout and the steam version of Receiver.

**Comment by autious** [comment]
This is still and issue, hopefully will be fixable with next major version of Unity.

**Comment by redcodefinal** [comment]
> 
> 
> This is still and issue, hopefully will be fixable with next major version of Unity.

it will not
